# config/meta.yml

meta_product_name: "AddressMover"
meta_title: "AddressMover - Changes your address with only a few clicks"
meta_description: "With AddressMover you change your address for all your service providers with only a few clicks."
meta_image: "address-logo.svg" # should exist in `app/assets/images/`
